### ISSUE TITLE
Замечания по lw3

### ISSUE THREAD

**Issue by ivklgn** [Rekazz/webdev-learn-2#1]
**HTML:**
1. Camel case не используется в именах файлов, id'шников, классов html (css)
```html
    <script src="scripts/regUser.js"></script>
```
используется reg-user.js, registration.js

2. Излишне использовать pattern
```html
<input type='email' id='email' placeholder='Эл. Почта' minlength="6" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}" required><span></span>
```

3. Поправить:
```html
<span></span>
```
идентифицировать по классу или лучше по id.

4. убрать checked
```html
<input type="checkbox" id="choice" checked required>
```
5. Переименовать id в форме `send` на адекватное. (адекватное: registration-form)
+ на этот id в обеих ветках вешается обработчик submit. (в чистом js addEventListener)

6. Во всех файлах если вы выбрали " ковычки, то использовать только их.

**CSS:**
1. Найти коды символов:
```css
 content: '✓';
 content: '✗';
```
2. Стилизацию на теги делать для общих стилей, для конкретных компонентов через id, class
```css
form {
  font-family: sans-serif;
  border: 1px solid #D4DADB;
  padding: 0 15px;
  border-radius: 3px;
  background-color: white;
}
```

kT=1.1
kQ=0.6
